name: Update Cloud Run data loader

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: dt-patrick-project-dev

jobs:
  # First, get the container into the GCR
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }} # can be base64 encoded or plain text
          registry: gcr.io
          project_id: ${{ env.PROJECT_ID }}
          image_name: forecast-data-loader
          image_tag: latest
  deploy-to-cloud-run:
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          image: 'gcr.io/${{ env.PROJECT_ID }}/forecast-data-loader:latest'
          service: 'forecast-data-loader'
          region: "europe-west2"