name: Update Cloud Run data loader

on:
  push:
    branches:
      - main
env:
  PROJECT_ID: dt-patrick-project-dev
  SERVICE: forecast-data-loader
  STAGING_BUCKET: bkt-pipeline-staging-f5399bba

jobs:
  # First, get the container into the GCR
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }} # can be base64 encoded or plain text
          registry: gcr.io
          project_id: ${{ env.PROJECT_ID }}
          image_name: forecast-data-loader
          image_tag: latest
    # Now, get it into Cloud Run
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE }} \
            --region europe-west2 \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest \
            --platform "managed" \
            --quiet \
            --max-instances 10 \
            --service-account 'forecast-accessor@${{ env.PROJECT_ID }}.iam.gserviceaccount.com' \
            --set-env-vars STAGING_BUCKET=${{ env.STAGING_BUCKET }} \
            --ingress internal
